apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notif-app-servicemonitor
  namespace: default
  labels:
    monitor-enabled: "true"
spec:
  endpoints:
    - interval: 15s
      port: svc-port
      scrapeTimeout: 14s
      path: "/actuator/prometheus"
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: notif-nodeport